import {
  splitHighwayBody,
  isCaliforniaRoadClosed,
  isCaliforniaRoadOpen,
  californiaRoadStatusOrNull,
} from '../roadUtil';

const I80_CA_SAMPLE_OPEN = `I 80
    [IN THE SAN FRANCISCO BAY AREA - SOLANO CO]
    NO TRAFFIC RESTRICTIONS ARE REPORTED FOR THIS AREA.

    [IN THE NORTHERN CALIFORNIA AREA & SIERRA NEVADA]
    NO TRAFFIC RESTRICTIONS ARE REPORTED FOR THIS AREA.
`;

const US50_CA_SAMPLE_NULL = `
US 50
  [IN THE SACRAMENTO VALLEY & THE LAKE TAHOE BASIN]
  1-WAY CONTROLLED TRAFFIC 5.6 MI EAST OF RIVERTON /AT ALDER CREEK RD/
(EL DORADO CO) FROM 0600 HRS TO 1800 HRS MONDAY THRU THURSDAY THRU 6/29/17
- DUE TO CONSTRUCTION

  IS REDUCED TO 1 LANE IN EACH DIRECTION FROM 3 MI EAST OF POLLOCK PINES TO
1 MI WEST OF RIVERTON /AT BRIDAL VEIL FALLS RD/ (EL DORADO CO) - DUE TO A
SLIPOUT - MOTORISTS ARE SUBJECT TO DELAYS`;

const US89_CA_SAMPLE_NULL = `SR 89
    [IN THE CENTRAL CALIFORNIA AREA & SIERRA NEVADA]
    NO TRAFFIC RESTRICTIONS ARE REPORTED FOR THIS AREA.

    [IN THE NORTHERN CALIFORNIA AREA & SIERRA NEVADA]
    IS CLOSED FROM THE LASSEN VOLCANIC NAT'L PARK SOUTH BDRY TO THE
JCT OF SR 44 /LASSEN LOOP/ (TEHAMA, SHASTA CO) - FOR THE WINTER - MOTORISTS ARE
ADVISED TO USE AN ALTERNATE ROUTE

    1-WAY CONTROLLED TRAFFIC FROM 2 MI SOUTH TO 1.7 MI SOUTH OF
BLISS STATE PARK (EL DORADO CO) FROM 0700 HRS TO 2000 HRS MONDAY THRU
THURSDAY THRU 6/29/17 - DUE TO CONSTRUCTION

    1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 2.2 MI NORTH OF THE
EL DORADO/PLACER CO LINE /AT FAWN ST/ TO 2.5 MI NORTH OF THE
EL DORADO/PLACER CO LINE /AT TROUT ST/ FROM 1000 HRS TO 1800 HRS MONDAY THRU
FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION

    1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM WARD CREEK TO
SPRUCE AVE /IN TAHOE CITY/ (PLACER CO) FROM 1900 HRS EACH NIGHT TO 1000 HRS
EACH MORNING MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO MAINTENANCE

    1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 4.5 MI NORTH OF THE
JCT OF SR 28 /AT TRUCKEE RIVER BRIDGE/ (PLACER CO) TO DONNER PASS RD
/IN TRUCKEE/ (NEVADA CO) FROM 1800 HRS EACH NIGHT TO 0600 HRS EACH MORNING
MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION

    1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM HOT SPRINGS RD TO
MILL ST /IN GREENVILLE/ (PLUMAS CO) FROM 0700 HRS TO 1800 HRS MONDAY THRU
FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION`;

test('can correctly detect a road as open', () => {
  expect(isCaliforniaRoadOpen(US50_CA_SAMPLE_NULL)).toBe(false);
  expect(isCaliforniaRoadClosed(US50_CA_SAMPLE_NULL)).toBe(false);
  expect(isCaliforniaRoadOpen(US89_CA_SAMPLE_NULL)).toBe(true);
  expect(isCaliforniaRoadClosed(US89_CA_SAMPLE_NULL)).toBe(true);
  expect(isCaliforniaRoadOpen(I80_CA_SAMPLE_OPEN)).toBe(true);
  expect(isCaliforniaRoadClosed(I80_CA_SAMPLE_OPEN)).toBe(false);

});

test('can correctly detect a road as closed', () => {

});

test('can correctly parse road status', () => {
  expect(californiaRoadStatusOrNull(US50_CA_SAMPLE_NULL)).toBe('incident');
  expect(californiaRoadStatusOrNull(US89_CA_SAMPLE_NULL)).toBe('ambiguous');
  expect(californiaRoadStatusOrNull(I80_CA_SAMPLE_OPEN)).toBe('open');


});











// test('splits at highways', () => {
//
//   const text = `HIGHWAY CONDITIONS REPORT AT 1545 HRS ON 6/27/17
//
// CALTRANS HIGHWAY INFORMATION NETWORK REPORTS THE FOLLOWING CURRENT HIGHWAY
//
// BE ALERT FOR FOG, CARRY TRACTION DEVICES IN MOUNTAIN AREAS AND WATCH FOR
// HIGHWAY MAINTENANCE PERSONNEL. "SLOW FOR THE CONE ZONE"
//
// TRAVEL IS NOT RECOMMENDED FOR CAMPERS, TRAILERS OR PERMIT LOADS IN THE AREAS
// WITH A HIGH WIND ADVISORY POSTED.
//
// PLEASE RESEARCH CHAIN CONTROL LOCATIONS AS CALTRANS IS CURRENTLY WORKING TO
// UPDATE CHAIN CONTROL DESCRIPTIONS FOR CONSISTENCY WITH INTERNET MAPPING,
// LIKE GOOGLE MAPS & MAPQUEST.
//
// ------------------------------------------------------------------------------
//
// SR 1
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     NO TRAFFIC RESTRICTIONS ARE REPORTED FOR THIS AREA.
//
//     [IN THE CENTRAL CALIFORNIA AREA]
//     IS CLOSED FROM 4.6 MI NORTH OF RAGGED POINT TO GORDA (MONTEREY CO) - DUE TO
// MUDSLIDE REMOVAL - MOTORISTS ARE ADVISED TO USE AN ALTERNATE ROUTE - MOTORISTS
// CAN ACCESS SR 1 FROM GORDA TO LIMEKILN STATE PARK BY USING
// NACIMIENTO-FERGUSON RD
//
//     IS CLOSED FROM LIMEKILN CREEK BRIDGE TO 0.5 MI SOUTH OF BIG SUR STATE PARK
// /IN BIG SUR/ (MONTEREY CO) - DUE TO MUDSLIDE REMOVAL & BRIDGE REPLACEMENT
// - MOTORISTS ARE ADVISED TO USE AN ALTERNATE ROUTE
//
//     IS CLOSED FROM 1 MI NORTH OF MUIR BEACH /AT SLIDE RANCH/ TO 0.2 MI SOUTH
// OF STINSON BEACH (MARIN CO) - DUE TO MUDSLIDE REMOVAL - MOTORISTS ARE ADVISED
// TO USE AN ALTERNATE ROUTE - LOCAL RESIDENTS WITH PROPER IDENTIFICATION WILL BE
// ALLOWED ACCESS
//
//     1-WAY CONTROLLED TRAFFIC FROM 13 MI NORTH TO 13.3 MI NORTH OF
// BIG SUR STATE PARK (MONTEREY CO) FROM 0600 HRS TO 1800 HRS TUESDAY
// THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 1.3 MI NORTH OF
// SANTA CRUZ /AT GRANITE ROCK PLANT RD/ TO 4.7 MI NORTH OF SANTA CRUZ
// /AT COAST RD/ (SANTA CRUZ CO) FROM 0900 HRS TO 1500 HRS MONDAY THRU FRIDAY
// THRU 6/30/17 - DUE TO UTILITY WORK
//
//     1-WAY CONTROLLED TRAFFIC FROM 2.3 MI NORTH OF THE JCT OF US 101
// /AT CHAMBERLAIN COURT/ TO 2.5 MI NORTH OF THE JCT OF US 101
// /AT WEST CALIFORNIA AVE/ (MARIN CO) FROM 0700 HRS TO 1700 HRS MONDAY
// THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 0.2 MI SOUTH OF THE
// SONOMA/MARIN CO LINE TO 0.2 MI NORTH OF THE MARIN/SONOMA CO LINE FROM 0700 HRS
// TO 1700 HRS 7 DAYS A WEEK THRU 10/4/18 - DUE TO MAINTENANCE
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 4.4 MI NORTH OF THE
// JCT OF SR 116 /AT RUSSIAN GULCH/ TO 6.3 MI SOUTH OF FORT ROSS
// /AT MEYERS GRADE RD/ (SONOMA CO) - DUE TO FLOOD DAMAGE REPAIR - MOTORISTS ARE
// SUBJECT TO DELAYS OF UP TO 30 MINUTES
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 10.1 MI NORTH TO
// 10.7 MI NORTH OF THE JCT OF SR 116 (SONOMA CO) 24 HRS A DAY 7 DAYS A WEEK THRU
// 0800 HRS ON 1/31/18 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 11.1 MI NORTH TO
// 12.4 MI NORTH OF THE JCT OF SR 116 (SONOMA CO) 24 HRS A DAY 7 DAYS A WEEK THRU
// 2359 HRS ON 8/31/17 - DUE TO CONSTRUCTION
//
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC 12 MI SOUTH OF THE JCT OF SR 211 /AT BRANSCOMB RD/
// (MENDOCINO CO) 24 HRS A DAY 7 DAYS A WEEK THRU 6/30/17 - DUE TO EMERGENCY WORK
//
//     1-WAY CONTROLLED TRAFFIC 7.5 MI SOUTH OF THE JCT OF SR 211 (MENDOCINO CO)
// 24 HRS A DAY 7 DAYS A WEEK THRU 6/30/17 - DUE TO EMERGENCY WORK
//
// SR 2
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     THE NORTHBOUND CONNECTOR TO EASTBOUND I 210 /IN GLENDALE/ (LOS ANGELES CO)
// IS CLOSED FROM 1900 HRS EACH NIGHT TO 0600 HRS EACH MORNING MONDAY THRU
// SATURDAY THRU 7/1/17 - DUE TO MAINTENANCE - A DETOUR IS AVAILABLE
//
//     IS CLOSED FROM THE JCT OF SR 39 TO 5.3 MI WEST OF BIG PINES
// /AT VINCENT GULCH RD/ (LOS ANGELES CO) - DUE TO A SINKHOLE - MOTORISTS
// ARE ADVISED TO USE AN ALTERNATE ROUTE
//
//     ALL TRACTOR-SEMI TRAILER COMBINATIONS WITH 3 AXLES OR GREATER ARE
// PROHIBITED FROM THE JCT OF I 210 /IN LA CANADA-FLINTRIDGE/ TO THE
// ANGELES FOREST HIGHWAY (LOS ANGELES CO) - ALTERNATE ROUTES ARE AVAILABLE
//
// SR 4
//     [IN THE CENTRAL CALIFORNIA AREA]
//     IS CLOSED FROM THE EAST END OF LAKE ALPINE TO 7.2 MI WEST OF THE
// JCT OF SR 89 /AT RAYMOND MEADOWS/ /EBBETTS PASS/ (ALPINE CO) - DUE TO
// CONSTRUCTION - MOTORISTS ARE ADVISED TO USE AN ALTERNATE ROUTE
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM WILLOW ST TO
// ARNOLD BYWAY /IN ARNOLD/ (CALAVERAS CO) FROM 0700 HRS TO 1800 HRS MONDAY THRU
// FRIDAY THRU 6/30/17 - DUE TO PERMIT WORK
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 1.1 MI EAST OF ARNOLD
// /AT UPPER MORAN RD/ TO 2.6 MI EAST OF ARNOLD /AT BIG TREES PARK ENTRANCE/
// (CALAVERAS CO) FROM 0600 HRS TO 1800 HRS MONDAY THRU FRIDAY THRU 6/30/17
// - DUE TO CONSTRUCTION
//
// SR 7
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     THE NORTHBOUND CONNECTOR TO WESTBOUND I 8 (IMPERIAL CO) IS CLOSED FROM
// 0500 HRS TO 1800 HRS MONDAY THRU FRIDAY THRU 8/24/17 - DUE TO CONSTRUCTION
// - A DETOUR IS AVAILABLE
//
// I 8
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     THE WESTBOUND CONNECTOR TO EASTBOUND & WESTBOUND SR 98 (IMPERIAL CO)
// IS CLOSED FROM 0001 HRS TO 1900 HRS MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO
// CONSTRUCTION - A DETOUR IS AVAILABLE
//
//     THE WESTBOUND CONNECTOR TO EASTBOUND & WESTBOUND SR 186 (IMPERIAL CO) IS
// CLOSED 24 HRS A DAY 7 DAYS A WEEK THRU 8/31/17 - DUE TO CONSTRUCTION
// - A DETOUR IS AVAILABLE
//
//     IS CLOSED TO WESTBOUND TRAFFIC FROM WINTERHAVEN DR /IN WINTERHAVEN/ TO
// THE JCT OF SR 186 (IMPERIAL CO) 24 HRS A DAY 7 DAYS A WEEK THRU 0500 HRS ON
// 8/16/17 - DUE TO CONSTRUCTION - A DETOUR IS AVAILABLE
//
// SR 9
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC 1.9 MI SOUTH OF THE SOUTH JCT OF SR 236
// /AT WESTERN AVE/ (SANTA CRUZ CO) 24 HRS A DAY 7 DAYS A WEEK THRU 1800 HRS ON
// 12/31/17 - DUE TO MAINTENANCE
//
// I 15
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     SOUTHBOUND TRAFFIC IS NO LONGER REDUCED TO 3 LANES AT ONTARIO AVE
// /IN CORONA/ (RIVERSIDE CO) AT 1515 HRS ON 6/27/17
//
// SR 20
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 5.6 MI WEST OF WILLITS
// TO HARMON LANE /IN WILLITS/ (MENDOCINO CO) FROM 0730 HRS TO 1800 HRS MONDAY
// THRU THURSDAY THRU 6/29/17 - DUE TO MAINTENANCE
//
//     1-WAY CONTROLLED TRAFFIC 3 MI EAST OF WASHINGTON RD (NEVADA CO) FROM
// 0600 HRS TO 2100 HRS MONDAY THRU THURSDAY THRU 6/29/17 - DUE TO UTILITY WORK
//
//     1-WAY CONTROLLED TRAFFIC 6.5 MI WEST OF THE JCT OF I 80 /AT LOWELL HILL RD/
// (NEVADA CO) FROM 0600 HRS TO 2100 HRS MONDAY THRU THURSDAY THRU 6/29/17 - DUE
// TO UTILITY WORK
//
// SR 23
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     IS CLOSED FROM THE JCT OF SR 1 TO 2.3 MI NORTH OF THE JCT OF SR 1
// /AT DECKER BOYS CAMP/ (LOS ANGELES CO) FROM 0700 HRS TO 1900 HRS 7 DAYS A WEEK
// - DUE TO SLIDE REMOVAL - MOTORISTS ARE ADVISED TO USE AN ALTERNATE ROUTE
//
//     1-WAY CONTROLLED TRAFFIC FROM THE JCT OF SR 1 TO 2.3 MI NORTH OF THE
// JCT OF SR 1 /AT DECKER BOYS CAMP/ (LOS ANGELES CO) FROM 1900 HRS EACH NIGHT
// TO 0700 HRS EACH MORNING 7 DAYS A WEEK - DUE TO SLIDE REMOVAL
//
// SR 26
//     [IN THE CENTRAL CALIFORNIA & SIERRA NEVADA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 7.4 MI EAST OF THE
// SAN JOAQUIN/CALAVERAS CO LINE /AT GEE LN/ TO 1.3 MI WEST OF THE JCT OF SR 12
// /AT COUNTY VIEW DR/ (CALAVERAS CO) FROM 1900 HRS EACH NIGHT TO 0700 HRS EACH
// MORNING MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO MAINTENANCE
//
// SR 32
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC FROM WEST 7TH ST TO WEST 9TH ST /IN CHICO/
// (BUTTE CO) FROM 0700 HRS TO 1900 HRS MONDAY THRU FRIDAY THRU 6/30/17 -
// DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC FROM WEST 9TH ST TO CHESTNUT ST /IN CHICO/
// (BUTTE CO) FROM 0700 HRS TO 2100 HRS MONDAY THRU FRIDAY THRU 6/30/17 -
// DUE TO CONSTRUCTION
//
// SR 35
//     [IN THE CENTRAL CALIFORNIA AREA]
//     IS CLOSED FROM 5 MI SOUTH OF THE JCT OF SR 9 /AT LAS CUMBRES RD/ TO THE
// JCT OF SR 9 /AT CASTLE ROCK RD/ (SANTA CLARA CO) - DUE TO A WASHOUT - MOTORISTS
// ARE ADVISED TO USE AN ALTERNATE ROUTE
//
//     1-WAY CONTROLLED TRAFFIC FROM 0.4 MI SOUTH OF WOODSIDE /AT ELK TREE RD/ TO
// 0.2 MI SOUTH OF WOODSIDE /AT CALAVERAS WAY/ (SAN MATEO CO) - DUE TO ROAD DAMAGE
//
// SR 36
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC 2.5 MI WEST OF BRIDGEVILLE /AT GOLDEN GATE DR/
// (HUMBOLDT CO) FROM 0800 HRS TO 2000 HRS 7 DAYS A WEEK THRU 7/20/17 - DUE TO
// CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC 1.2 MI WEST OF SOUTH FORK MOUNTAIN (TRINITY CO)
// FROM 0600 HRS TO 1800 HRS MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 8.2 MI WEST TO 4.7 MI
// WEST OF THE JCT OF SR 172 (TEHAMA CO) FROM 0600 HRS TO 1900 HRS MONDAY THRU
// FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 3.1 MI WEST TO 0.6 MI
// WEST OF PLATINA (SHASTA CO) FROM 0730 HRS TO 1600 HRS MONDAY THRU TUESDAY THRU
// 6/27/17 - DUE TO MAINTENANCE
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM THE EAST JCT OF SR 172
// (TEHAMA CO) TO 5.3 MI WEST OF CHESTER (PLUMAS CO) FROM 0700 HRS TO 1900 HRS
// MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
// SR 39
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     IS CLOSED FROM 4.4 MI SOUTH OF THE JCT OF SR 2 TO THE JCT OF SR 2
// (LOS ANGELES CO) 24 HRS A DAY 7 DAYS A WEEK THRU 0500 HRS ON 11/30/20 - DUE TO
// CONSTRUCTION - MOTORISTS ARE ADVISED TO USE AN ALTERNATE ROUTE
//
// SR 41
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC 1.2 MI NORTH OF FRESNO /AT THE SAN JOAQUIN RIVER/
// (FRESNO CO) 24 HRS A DAY 7 DAYS A WEEK THRU 11/30/18 - DUE TO BRIDGE REPAIR
//
//     [YOSEMITE NAT'L PARK]
//     FOR YOSEMITE NAT'L PARK ROAD INFORMATION CALL 209-372-0200
//
// SR 46
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 8.6 MI EAST TO 9.5 MI
// EAST OF THE JCT OF SR 1 (SAN LUIS OBISPO CO) FROM 0700 HRS TO 1600 HRS MONDAY
// THRU FRIDAY THRU 6/30/17 - DUE TO UTILITY WORK
//
// SR 49
//     [IN THE CENTRAL CALIFORNIA AREA]
//     NO TRAFFIC RESTRICTIONS ARE REPORTED FOR THIS AREA.
//
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC FROM 6.7 MI NORTH TO 8.9 MI NORTH OF NEVADA CITY
// (NEVADA CO) 24 HRS A DAY 7 DAYS A WEEK THRU 2359 HRS ON 6/30/17 - DUE TO SLIDE
// REMOVAL
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 14.2 MI SOUTH OF
// DOWNIEVILLE TO EWIS LANE / IN SIERRA CITY/ (SIERRA CO) FROM 0700 HRS TO
// 1530 HRS MONDAY THRU THURSDAY THRU 6/29/17 - DUE TO MAINTENANCE
//
//     1-WAY CONTROLLED TRAFFIC FROM YUBA PASS SUMMIT TO SATTLEY (SIERRA CO)
// - DUE TO FLOOD DAMAGE REPAIRS
//
//     MOTORISTS ARE SUBJECT TO DELAYS OF UP TO 20 MINUTES FROM THE
// YUBA/SIERRA CO LINE TO YUBA PASS SUMMIT (SIERRA CO) - DUE TO STORM CLEANUP
// - PLEASE DRIVE WITH CAUTION
//
// US 50
//     [IN THE SACRAMENTO VALLEY & THE LAKE TAHOE BASIN]
//     1-WAY CONTROLLED TRAFFIC 5.6 MI EAST OF RIVERTON /AT ALDER CREEK RD/
// (EL DORADO CO) FROM 0600 HRS TO 1800 HRS MONDAY THRU THURSDAY THRU 6/29/17
// - DUE TO CONSTRUCTION
//
//     IS REDUCED TO 1 LANE IN EACH DIRECTION FROM 3 MI EAST OF POLLOCK PINES TO
// 1 MI WEST OF RIVERTON /AT BRIDAL VEIL FALLS RD/ (EL DORADO CO) - DUE TO A
// SLIPOUT - MOTORISTS ARE SUBJECT TO DELAYS
//
// SR 58
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     WESTBOUND TRAFFIC IS REDUCED TO 1 LANE FROM 0.4 MI WEST OF BARSTOW
// /AT AGATE RD/ TO 1.4 MI WEST OF BARSTOW /AT COMMUNITY BLVD/ (SAN BERNARDINO CO)
// 24 HRS A DAY 7 DAYS A WEEK THRU 0800 HRS ON 7/31/17 - DUE TO CONSTRUCTION
//
//     [IN THE CENTRAL CALIFORNIA AREA]
//     IS CLOSED FROM THE JCT OF SR 229 TO 3 MI EAST OF THE JCT OF SR 229
// (SAN LUIS OBISPO CO) - DUE TO A WILDFIRE - MOTORISTS ARE ADVISED TO USE
// AN ALTERNATE ROUTE
//
// SR 65
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 9.3 MI NORTH OF THE
// JCT OF SR 99 TO 9.1 MI SOUTH OF THE JCT OF SR 155 (TULARE CO) FROM 1800 HRS
// EACH NIGHT TO 0500 HRS EACH MORNING MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO
// CONSTRUCTION
//
//     [IN THE NORTHERN CALIFORNIA AREA]
//     NO TRAFFIC RESTRICTIONS ARE REPORTED FOR THIS AREA.
//
// SR 70
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC FROM 1 MI EAST TO 1.5 MI EAST OF THE
// BUTTE/PLUMAS CO LINE FROM 0700 HRS TO 1700 HRS MONDAY THRU FRIDAY
// THRU 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 7 MI EAST TO 9 MI EAST
// OF QUINCY (PLUMAS CO) 24 HRS A DAY 7 DAYS A WEEK THRU 11/15/17 - DUE TO
// CONSTRUCTION
//
//     TRACTOR-SEMITRAILER COMBINATIONS OVER 65 FEET & ALL TRACTOR-SEMITRAILER
// COMBINATIONS /DOUBLES/ OVER 75 FEET IN TOTAL LENGTH ARE PROHIBITED FROM
// 13 MI EAST OF THE JCT OF SR 191 TO THE NORTH JCT OF SR 89 /GREENVILLE WYE/
// (PLUMAS CO) - ALTERNATE ROUTES ARE AVAILABLE
//
// SR 76
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 4 MI EAST OF RINCON
// /AT RED GATE RD/ TO 10.7 MI EAST OF RINCON (SAN DIEGO CO) FROM 0900 HRS TO
// 1600 HRS MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
// SR 84
//     [IN THE CENTRAL CALIFORNIA AREA]
//     IS CLOSED AT THE CACHE SLOUGH FERRY (SOLANO CO) - DUE TO
// MECHANICAL PROBLEMS - MOTORISTS ARE ADVISED TO USE AN ALTERNATE ROUTE
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 2.7 MI NORTH
// OF THE JCT OF SR 1 /AT BEAR GULCH RD/ TO 3.8 MI NORTH OF THE JCT OF SR 1
// (SAN MATEO CO) FROM 0700 HRS TO 1700 HRS TUESDAY THRU FRIDAY THRU 6/30/17
// - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC FROM THE JCT OF SR 35 TO GRAND VIEW AVE
// /IN WOODSIDE/ (SAN MATEO CO) - DUE TO SLIDE REMOVAL
//
// SR 88
//     [IN THE CENTRAL CALIFORNIA & SIERRA NEVADA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM COURT ST /IN JACKSON/ TO
// 9.6 MI EAST OF PINE GROVE /AT SILVER DR/ (AMADOR CO) FROM 1900 HRS EACH NIGHT
// TO 0600 HRS EACH MORNING MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
// SR 89
//     [IN THE CENTRAL CALIFORNIA AREA & SIERRA NEVADA]
//     NO TRAFFIC RESTRICTIONS ARE REPORTED FOR THIS AREA.
//
//     [IN THE NORTHERN CALIFORNIA AREA & SIERRA NEVADA]
//     IS CLOSED FROM THE LASSEN VOLCANIC NAT'L PARK SOUTH BDRY TO THE
// JCT OF SR 44 /LASSEN LOOP/ (TEHAMA, SHASTA CO) - FOR THE WINTER - MOTORISTS ARE
// ADVISED TO USE AN ALTERNATE ROUTE
//
//     1-WAY CONTROLLED TRAFFIC FROM 2 MI SOUTH TO 1.7 MI SOUTH OF
// BLISS STATE PARK (EL DORADO CO) FROM 0700 HRS TO 2000 HRS MONDAY THRU
// THURSDAY THRU 6/29/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 2.2 MI NORTH OF THE
// EL DORADO/PLACER CO LINE /AT FAWN ST/ TO 2.5 MI NORTH OF THE
// EL DORADO/PLACER CO LINE /AT TROUT ST/ FROM 1000 HRS TO 1800 HRS MONDAY THRU
// FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM WARD CREEK TO
// SPRUCE AVE /IN TAHOE CITY/ (PLACER CO) FROM 1900 HRS EACH NIGHT TO 1000 HRS
// EACH MORNING MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO MAINTENANCE
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 4.5 MI NORTH OF THE
// JCT OF SR 28 /AT TRUCKEE RIVER BRIDGE/ (PLACER CO) TO DONNER PASS RD
// /IN TRUCKEE/ (NEVADA CO) FROM 1800 HRS EACH NIGHT TO 0600 HRS EACH MORNING
// MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM HOT SPRINGS RD TO
// MILL ST /IN GREENVILLE/ (PLUMAS CO) FROM 0700 HRS TO 1800 HRS MONDAY THRU
// FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
// SR 92
//     [IN THE CENTRAL CALIFORNIA AREA]
//     THE EASTBOUND CONNECTOR TO SOUTHBOUND SR 82 /IN SAN MATEO/ (SAN MATEO CO)
// IS CLOSED FROM 1000 HRS TO 1500 HRS MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO
// CONSTRUCTION - A DETOUR IS AVAILABLE
//
// SR 94
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM MELODY RD TO
// RANCHO JAMUL DR /IN JAMUL/ (SAN DIEGO CO) FROM 0600 HRS TO 1600 HRS MONDAY THRU
// FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM THE JCT OF SR 188 TO THE
// JCT OF I 8 (SAN DIEGO CO) FROM 0700 HRS TO 1800 HRS TUESDAY THRU FRIDAY THRU
// 6/30/17 - DUE TO CONSTRUCTION
//
// SR 96
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 3.3 MI WEST TO 2.7 MI
// WEST OF HOOPA (HUMBOLDT CO) FROM 0700 HRS TO 1700 HRS MONDAY THRU FRIDAY THRU
// 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC 0.9 MI WEST OF THE JCT OF SR 169 /IN WEITCHPEC/
// (HUMBOLDT CO) 24 HRS A DAY 7 DAYS A WEEK THRU 7/31/17 - DUE TO
// STORM DAMAGE REPAIR
//
// SR 98
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     IS CLOSED FROM LACY ST TO CESAR CHAVEZ BLVD /IN CALEXICO/ (IMPERIAL CO)
// FROM 0001 HRS TO 1800 HRS 7 DAYS A WEEK THRU 8/26/17 - DUE TO CONSTRUCTION
// - A DETOUR IS AVAILABLE
//
//     THE EASTBOUND CONNECTOR TO WESTBOUND I 8 (IMPERIAL CO) IS CLOSED FROM
// 0001 HRS TO 1900 HRS TUESDAY THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
// - A DETOUR IS AVAILABLE
//
// US 101
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     NO TRAFFIC RESTRICTIONS ARE REPORTED FOR THIS AREA.
//
//     [IN THE CENTRAL CALIFORNIA AREA]
//     NO TRAFFIC RESTRICTIONS ARE REPORTED FOR THIS AREA.
//
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC 12.3 MI NORTH OF THE JCT OF SR 271
// /AT DORA CREEK BRIDGE/ (MENDOCINO CO) 24 HRS A DAY 7 DAYS A WEEK THRU 6/30/17
// - DUE TO EMERGENCY REPAIRS
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 4.1 MI NORTH OF THE
// JCT OF SR 162 TO 8.7 MI SOUTH OF LEGGET (MENDOCINO CO) FROM 1900 HRS EACH NIGHT
// TO 0700 HRS EACH MORNING MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM COMMERCIAL ST
// /IN WILLITS/ TO 1 MI NORTH OF WILLITS (MENDOCINO CO) FROM 0700 HRS TO
// 1500 HRS MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC FROM 10.6 MI NORTH TO 11 MI NORTH OF TRINIDAD
// (MENDOCINO CO) FROM 0700 HRS TO 1930 HRS 7 DAYS A WEEK THRU 10/1/17 - DUE TO
// COMNSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC FROM THE JCT OF SR 1 /IN LEGGETT/ TO 15 MI SOUTH
// OF GARBERVILLE (MENDOCINO CO) - DUE TO A ROCK SLIDE
//
//     1-WAY CONTROLLED TRAFFIC 3.5 MI SOUTH OF DRY LAGOON STATE PARK
// (HUMBOLDT CO) 24 HRS A DAY 7 DAYS A WEEK THRU 1930 HRS ON 10/1/17
// - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 7.4 MI NORTH TO 10.6 MI
// NORTH OF THE JCT OF SR 169 (DEL NORTE CO) 24 HRS A DAY 7 DAYS A WEEK THRU
// 12/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 13.7 MI SOUTH TO
// 10.5 MI SOUTH OF CRESCENT CITY (DEL NORTE CO) FROM 0600 HRS TO 2000 HRS THRU
// 12/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 8.5 MI SOUTH TO 8.1 MI
// SOUTH OF CRESCENT CITY (DEL NORTE CO) FROM 0600 HRS TO 2000 HRS THRU 12/31/17
// - DUE TO MAINTENANCE
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 5.2 MI SOUTH TO 3.5 MI
// SOUTH OF CRESCENT CITY (DEL NORTE CO) FROM 0700 HRS TO 1500 HRS THRU 12/31/17
// - DUE TO MAINTENANCE
//
//     IS REDUCED TO 1 LANE IN EACH DIRECTION FROM 5.6 MI NORTH TO 6.3 MI NORTH
// OF THE JCT OF SR 271 (HUMBOLDT CO) - DUE TO STORM DAMAGE REPAIR
//
// SR 113
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 4 MI NORTH OF
// THE JCT OF SR 12 TO 0.8 MI SOUTH OF DIXON /AT MIDWAY RD/ (SOLANO CO) FROM
// 0700 HRS TO 1730 HRS MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
// SR 116
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC 6.8 MI EAST OF GUERNEVILLE /AT MAYS CANYON RD EAST/
// (SONOMA CO) 24 HRS A DAY 7 DAYS A WEEK THRU 1700 HRS ON 8/31/17 - DUE TO
// MAINTENANCE
//
// SR 120
//     [IN THE CENTRAL CALIFORNIA AREA & SIERRA NEVADA]
//     IS CLOSED 4.2 MI WEST OF THE SOUTH JCT OF SR 49 /AT TUOLUMNE RIVER BRIDGE/
// (TUOLUMNE CO) FROM 1700 HRS EACH NIGHT TO 0700 HRS EACH MORNING SUNDAY THRU
// FRIDAY THRU 9/29/17 - DUE TO BRIDGE WORK - MOTORISTS ARE ADVISED TO USE AN
// ALTERNATE ROUTE
//
//     IS CLOSED FROM CRANE FLAT TO THE YOSEMITE NATIONAL PARK BOUNDARY
// /TIOGA PASS/ (TUOLUMNE, MONO CO) - FOR THE WINTER - MOTORISTS ARE ADVISED TO
// USE AN ALTERNATE ROUTE
//
//     1-WAY CONTROLLED TRAFFIC 4.2 MI WEST OF THE SOUTH JCT OF SR 49
// /AT TUOLUMNE RIVER BRIDGE/ (TUOLUMNE CO) FROM 0700 HRS TO 1700 HRS MONDAY
// THRU THURSDAY & 24 HRS A DAY FROM 0700 HRS FRIDAY TO 1700 HRS SUNDAY THRU
// 9/29/17 - DUE TO BRIDGE WORK
//
//     [YOSEMITE NAT'L PARK]
//     FOR YOSEMITE NAT'L PARK ROAD INFORMATION CALL 209-372-0200
//
// SR 121
//     [IN THE CENTRAL CALIFORNIA AREA]
//     IS CLOSED FROM HAGEN RD TO TRANCAS ST /IN NAPA/ (NAPA CO) FROM 1000 HRS TO
// 1700 HRS 7 DAYS A WEEK THRU 11/5/17 - DUE TO BRIDGE CONSTRUCTION - A DETOUR IS
// AVAILABLE
//
// SR 128
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC 3.5 MI WEST OF THE NORTH JCT OF US 101 (SONOMA CO)
// 24 HRS A DAY 7 DAYS A WEEK THRU 1700 HRS ON 7/31/17 - DUE TO CONSTRUCTION
//
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC 10 MI EAST OF THE JCT OF SR 253 /AT BEEBE CREEK/
// (MENDOCINO CO) 24 HRS A DAY 7 DAYS A WEEK THRU 7/31/17 - DUE TO ROADWAY
// EXCAVATION
//
//     1-WAY CONTROLLED TRAFFIC FROM TAYLOR ST TO MAIN ST /IN WINTERS/ (YOLO CO)
// FROM 0700 HRS TO 1430 HRS MONDAY THRU THURSDAY THRU 6/29/17 - DUE TO UTILITY
// WORK
//
// SR 130 - MT HAMILTON RD
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 4 MI EAST OF
// THE JCT OF I 680 /AT CROTHERS RD/ TO 4.5 MI EAST OF THE JCT OF I 680
// /AT CLAYTON RD/ (SANTA CLARA CO) 24 HRS A DAY 7 DAYS A WEEK THRU 1600 HRS
// ON 10/30/17 - DUE TO CONSTRUCTION
//
// SR 132
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 1.1 MI EAST TO
// 2.5 MI EAST OF THE SAN JOAQUIN/STANISLAUS CO LINE FROM 2000 HRS EACH NIGHT TO
// 0500 HRS EACH MORNING MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
// SR 137
//     [IN THE CENTRAL CALIFORNIA AREA]
//     IS CLOSED AT THE JCT OF SR 43 (KINGS CO) 24 HOURS A DAY 7 DAYS A WEEK THRU
// 1700 HRS ON 7/14/17 - DUE TO CONSTRUCTION - A DETOUR IS AVAILABLE
//
// SR 140
//     [IN THE CENTRAL CALIFORNIA AREA]
//     VEHICLES OVER 45 FEET ARE PROHIBITED & 1-WAY CONTROLLED TRAFFIC FOR ALL
// OTHER VEHICLES 20 MI EAST OF MARIPOSA (MARIPOSA CO) 24 HRS A DAY 7 DAYS A WEEK
// - DUE TO SLIDE REPAIRS
//
//     [YOSEMITE NAT'L PARK]
//     FOR YOSEMITE NAT'L PARK ROAD INFORMATION CALL 209-372-0200
//
// SR 147
//     [IN THE NORTHERN CALIFORNIA AREA]
//     IS CLOSED FROM 7.3 MI NORTH OF THE JCT OF SR 89 /AT BIG SPRINGS RD/
// (PLUMAS CO) TO 0.4 MI SOUTH OF THE PLUMAS/LASSEN CO LINE FROM FROM 0700 HRS
// TO 1900 HRS 7 DAYS A WEEK THRU 11/1/17 - DUE TO BRIDGE WORK - A DETOUR IS
// AVAILABLE
//
// SR 152
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC 1.8 MI EAST OF WATSONVILLE (SANTA CRUZ CO) FROM
// 1900 HRS EACH NIGHT TO 0700 HRS EACH MORNING MONDAY THRU FRIDAY THRU 6/30/17
// - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT THE SANTA CRUZ/SANTA CLARA CO LINE FROM
// 0700 HRS TO 1530 HRS MONDAY THRU THURSDAY THRU 6/29/17 - DUE TO CONSTRUCTION
//
// SR 154
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM BASE LINE AVE
// /IN SANTA YNEZ/ TO 8.6 MI WEST OF THE JCT OF SR 192
// /AT COLD SPRING CANYON BRIDGE/ (SANTA BARBARA CO) FROM 1930 HRS EACH NIGHT TO
// 0530 HRS EACH MORNING MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO MAINTENANCE
//
// SR 155
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 12.9 MI EAST OF
// GLENNVILLE /AT RANCHERIA RD/ TO 6.4 MI WEST OF WOFFORD HEIGHTS
// /AT ALTA SIERRA RD/ (KERN CO) FROM 0700 HRS TO 1700 HRS TUESDAY THRU FRIDAY
// THRU 6/30/17 - DUE TO CONSTRUCTION
//
// SR 162
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 8 MI WEST OF DOS RIOS
// /AT BLOODY RUN CREEK BRIDGE/ TO 7 MI WEST OF DOS RIOS
// /AT SOUTH EEL RIVER BRIDGE/ (MENDOCINO CO) 24 HRS A DAY THRU 1500 HRS ON
// 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC 7.4 MI EAST OF DOS RIOS /AT FAIRBANKS LN/
// (MENDOCINO CO) 24 HOURS A DAY 7 DAYS A WEEK THRU 2359 HRS ON 7/31/17 - DUE TO
// CONSTRUCTION
//
// SR 168
//     [IN THE CENTRAL CALIFORNIA AREA & SIERRA NEVADA]
//     1-WAY CONTROLLED TRAFFIC FROM AUBERRY RD /IN PRATHER/ TO 0.3 MI EAST OF
// PRATHER (FRESNO CO) FROM 1800 HRS EACH NIGHT TO 0600 HRS EACH MORNING MONDAY
// THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC FROM 0.6 MI EAST TO 0.8 MI EAST OF SHAVER LAKE
// (FRESNO CO) FROM 0700 HRS TO 1630 HRS TUESDAY THRU FRIDAY THRU 6/30/17 - DUE
// TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC 4 MI EAST OF SHAVER LAKE (FRESNO CO) FROM 0700 HRS
// TO 1630 HRS TUESDAY THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
// SR 169
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM WAUTECK VILLAGE TO
// 5.4 MI EAST OF PECWAN (HUMBOLDT CO) FROM 0800 HRS TO 1700 HRS MONDAY THRU
// FRIDAY THRU 6/30/17 - DUE TO UTILITY WORK
//
// SR 173
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 0.9 MI WEST OF THE
// JCT OF SR 189 /AT EMERALD DR/ TO 0.7 MI WEST OF THE JCT OF SR 189 /AT WALNUT DR/
// (SAN BERNARDINO CO) FROM 0800 HRS TO 1600 HRS MONDAY THRU FRIDAY THRU 6/30/17
// - DUE TO PERMIT WORK
//
// SR 175
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 5.9 MI WEST TO 1.3 MI
// WEST OF THE MENDOCINO/LAKE CO LINE 24 HRS A DAY THRU 1500 HRS ON 9/29/17 - DUE
// TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC FROM 1.1 MI WEST TO 0.7 MI WEST OF THE
// MENDOCINO/LAKE CO LINE 24 HRS A DAY THRU 2359 HRS ON 5/31/18 - DUE TO
// CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 7.5 MI WEST TO 6.5 MI
// WEST OF MIDDLETOWN (LAKE CO) FROM 0600 HRS TO 1700 HRS MONDAY THRU FRIDAY THRU
// 6/30/17 - DUE TO CONSTRUCTION
//
// SR 180
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 2.3 MI EAST TO 3 MI EAST
// OF MENDOTA (FRESNO CO) FROM 0600 HRS TO 1800 HRS TUESDAY THRU FRIDAY THRU
// 6/30/17 - DUE TO CONSTRUCTION
//
// SR 186
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     THE NORTHBOUND CONNECTOR TO WESTBOUND I 8 (IMPERIAL CO) IS CLOSED 24 HRS A
// DAY 7 DAYS A WEEK THRU 1800 HRS ON 8/31/17 - DUE TO CONSTRUCTION - A DETOUR IS
// AVAILABLE
//
// SR 191
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 4.8 MI NORTH OF
// THE JCT OF SR 70 /AT CLEAR CREEK CEMETERY RD/ TO 0.8 MI SOUTH OF PARADISE
// /AT AIRPORT RD/ (BUTTE CO) 24 HRS A DAY FROM 0600 HRS MONDAY TO 2000 HRS
// SATURDAY THRU 12/30/17 - DUE TO CONSTRUCTION - MOTORISTS ARE SUBJECT TO
// DELAYS OF UP TO 20 MINUTES
//
// SR 193
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT THE JCT OF SR 49 /IN PLACERVILLE/
// (EL DORADO CO) 24 HRS A DAY 7 DAYS A WEEK THRU 2359 HRS ON 8/31/17
// - DUE TO MUDSLIDE REMOVAL
//
// SR 198
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC FROM 0.7 MI EAST TO 1 MI EAST OF THE JCT OF SR 269
// /AT SISKIYOU AVE/ (FRESNO CO) 24 HRS A DAY 7 DAYS A WEEK THRU 1200 HRS ON
// 7/28/17 - DUE TO BRIDGE WORK
//
// US 199
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 0.3 MI SOUTH TO 0.7 MI
// NORTH OF THE JCT OF SR 197 (DEL NORTE CO) FROM 0800 HRS TO 1800 HRS ON 6/27/17
// - DUE TO MAINTENANCE
//
//     1-WAY CONTROLLED TRAFFIC FROM 2.2 MI NORTH TO 2.4 MI NORTH OF HIOUCHI
// (DEL NORTE CO) 24 HRS A DAY 7 DAYS A WEEK THRU 1900 HRS ON 10/31/17 - DUE
// TO CONSTRUCTION
//
// SR 201
//     [IN THE CENTRAL CALIFORNIA AREA]
//     IS CLOSED TO TRAFFIC FROM 1.9 MI NORTH TO 2.9 MI NORTH OF THE
// FRESNO/TULARE CO LINE 24 HRS A DAY 7 DAYS A WEEK THRU 2359 HRS ON
// 7/3/17 - DUE TO FLOODING - A DETOUR IS AVAILABLE
//
// SR 202
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 6.4 MI WEST OF THE
// JCT OF SR 58 /AT BANDUCCI RD/ TO 5.4 MI WEST OF THE JCT OF SR 58 /AT SCHOUT RD/
// (KERN CO) FROM 0700 HRS TO 1630 HRS ON 6/27/17 - DUE TO MAINTENANCE
//
// SR 203
//     [IN THE CENTRAL CALIFORNIA AREA & SIERRA NEVADA]
//     IS CLOSED FROM THE MAMMOTH MOUNTAIN INN (MONO CO) TO THE
// MONO/MADERA CO LINE - FOR THE WINTER - MOTORISTS ARE ADVISED TO USE
// AN ALTERNATE ROUTE
//
// SR 216
//     [IN THE CENTRAL CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM WELLS ST /IN WOODLAKE/
// TO THE JCT OF SR 198 (TULARE CO) FROM 0500 HRS TO 1800 HRS TUESDAY THRU FRIDAY
// THRU 6/30/17 - DUE TO CONSTRUCTION
//
// SR 243
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 6 MI NORTH OF THE
// JCT OF SR 74 TO 6.5 MI NORTH OF THE JCT OF SR 243 /AT ALPINE WAY/
// (RIVERSIDE CO) 24 HRS A DAY 7 DAYS A WEEK THRU 2300 HRS ON 6/30/17 - DUE TO
// CONSTRUCTION
//
// SR 247
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 4.8 MI NORTH OF
// YUCCA VALLEY /AT HANDLEY RD/ TO 15.4 MI NORTH OF YUCCA VALLEY /AT BOONE AVE/
// (SAN BERNARDINO CO) FROM 0500 HRS TO 1900 HRS MONDAY THRU THURSDAY THRU 6/29/17
// - DUE TO CONSTRUCTION
//
// SR 253
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 1 MI EAST TO 2 MI EAST
// OF THE JCT OF SR 128 (MENDOCINO CO) FROM 0700 HRS TO 1700 HRS 7 DAYS A WEEK
// THRU 10/31/17 - DUE TO CONSTRUCTION
//
// SR 254
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC 1.9 MI SOUTH OF PHILLIPSVILLE
// /AT OHMAN CREEK BRIDGE/ (HUMBOLDT CO) 24 HRS A DAY 7 DAYS A WEEK THRU 2000 HRS
// ON 8/31/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC 3.7 MI NORTH OF MIRANDA /AT ELK CREEK BRIDGE/
// (HUMBOLDT CO) FROM 0800 HRS TO 2000 HRS MONDAY THRU FRIDAY THRU 6/30/17 - DUE
// TO MAINTENANCE
//
//     1-WAY CONTROLLED TRAFFIC 5.5 MI NORTH OF HOLMES FLAT /AT BEAR CREEK BRIDGE/
// (HUMBOLDT CO) 24 HRS A DAY 7 DAYS A WEEK THRU 2000 HRS ON 6/30/17 - DUE TO
// CONSTRUCTION
//
// SR 284
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM THE JCT OF SR 70 TO 3 MI
// NORTH OF THE JCT OF SR 70 (PLUMAS CO) FROM 0800 HRS TO 1600 HRS MONDAY THRU
// THURSDAY THRU 6/29/17 - DUE TO MAINTENANCE
//
// SR 299
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 9.6 MI WEST OF
// THE JCT OF SR 96 /AT TITLOW HILL RD/ TO 1 MI WEST OF THE JCT OF SR 96
// (HUMBOLDT CO) FROM 0700 HRS TO 1800 HRS MONDAY THRU FRIDAY THRU 6/30/17
// - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 0.4 MI EAST TO 1.4 MI
// EAST OF SALYER (TRINITY CO) FROM 0800 HRS TO 1700 HRS MONDAY THRU FRIDAY THRU
// 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 0.5 MI EAST TO
// 1.5 MI EAST OF BURNT RANCH (TRINITY CO) - DUE TO SLIDE REMOVAL
//
//     1-WAY CONTROLLED TRAFFIC FROM 4.5 MI WEST OF BIG BAR /AT BIG FRENCH CREEK/
// TO 4.1 MI WEST OF BIG BAR (TRINITY CO) 24 HRS A DAY FROM 0600 HRS MONDAY TO
// 0600 HRS SUNDAY - DUE TO SLIDE REMOVAL - MOTORISTS ARE SUBJECT TO DELAYS OF
// UP TO 30 MINUTES FROM 1800 HRS EACH NIGHT TO 0600 HRS EACH MORNING -
// THE ROAD WILL BE OPEN TO ALL TRAFFIC FROM 0600 HRS SUNDAY TO 0600 HRS MONDAY
// WITH UP TO 15 MINUTE DELAYS
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 5.2 MI WEST TO 3.7 MI
// WEST OF BURNEY (SHASTA CO) FROM 0700 HRS TO 1800 HRS MONDAY THRU FRIDAY THRU
// 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 6.8 MI WEST TO 5.8 MI
// WEST OF THE EAST JCT OF SR 139 (MODOC CO) FROM 0600 HRS TO 1630 HRS ON 6/27/17
// - DUE TO MAINTENANCE
//
// US 395
//     [IN THE SOUTHERN CALIFORNIA AREA]
//     NO TRAFFIC RESTRICTIONS ARE REPORTED FOR THIS AREA.
//
//     [IN THE CENTRAL CALIFORNIA AREA & SIERRA NEVADA]
//     1-WAY CONTROLLED TRAFFIC 1.5 MI SOUTH OF INDEPENDENCE (INYO) - DUE TO
// ROADWAY REPAIRS
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM THE JCT OF SR 270
// TO 3.2 MI NORTH OF THE JCT OF SR 270 /AT POINT RANCH CURVE/ (MONO CO) FROM
// 0600 HRS TO 1800 HRS MONDAY THRU FRIDAY THRU 6/30/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC AT VARIOUS LOCATIONS FROM 13.3 MI SOUTH OF THE
// NEVADA STATE LINE /AT MILL CREEK DR/ TO 7.4 MI SOUTH OF THE NEVADA STATE LINE
// /AT MONEGHAN ST/ (MONO CO) FROM 0600 HRS TO 1800 HRS TUESDAY THRU FRIDAY THRU
// 6/30/17 - DUE TO CONSTRUCTION
//
//     [IN THE NORTHERN CALIFORNIA AREA]
//     NO TRAFFIC RESTRICTIONS ARE REPORTED FOR THIS AREA.
//
//
// CALTRANS/SACTO/AS
//   `;
//
//   const sr254Body = splitHighwayBody(text)['sr254'];
//
//   const report = `
//     [IN THE NORTHERN CALIFORNIA AREA]
//     1-WAY CONTROLLED TRAFFIC 1.9 MI SOUTH OF PHILLIPSVILLE
// /AT OHMAN CREEK BRIDGE/ (HUMBOLDT CO) 24 HRS A DAY 7 DAYS A WEEK THRU 2000 HRS
// ON 8/31/17 - DUE TO CONSTRUCTION
//
//     1-WAY CONTROLLED TRAFFIC 3.7 MI NORTH OF MIRANDA /AT ELK CREEK BRIDGE/
// (HUMBOLDT CO) FROM 0800 HRS TO 2000 HRS MONDAY THRU FRIDAY THRU 6/30/17 - DUE
// TO MAINTENANCE
//
//     1-WAY CONTROLLED TRAFFIC 5.5 MI NORTH OF HOLMES FLAT /AT BEAR CREEK BRIDGE/
// (HUMBOLDT CO) 24 HRS A DAY 7 DAYS A WEEK THRU 2000 HRS ON 6/30/17 - DUE TO
// CONSTRUCTION
//
// `;
//
//   expect(sr254Body).toMatchObject({
//     name: 'SR 254',
//     report,
//   })
// });
